### ISSUE TITLE
Error when installing meld-openmm-plugin

### ISSUE THREAD

**Issue by wtren** [maccallumlab/meld-openmm-plugin#11]
I met some problems when installing meld-openmm-plugin, the error messages are:

In file included from /home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:6:
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:9:26: error: openmm/Force.h: No such file or directory
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:10:25: error: openmm/Vec3.h: No such file or directory
In file included from /home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:7:
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/internal/MeldForceImpl.h:10:39: error: openmm/internal/ForceImpl.h: No such file or directory
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/internal/MeldForceImpl.h:11:27: error: openmm/Kernel.h: No such file or directory
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:9:36: error: openmm/OpenMMException.h: No such file or directory
In file included from /home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:6:
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: 'OpenMM' has not been declared
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: expected `{' before 'Force'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: function definition does not declare parameters
In file included from /home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:7:
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/internal/MeldForceImpl.h:19: error: 'OpenMM' has not been declared
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/internal/MeldForceImpl.h:19: error: expected `{' before 'ForceImpl'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/internal/MeldForceImpl.h:19: error: function definition does not declare parameters
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:13: error: 'OpenMM' is not a namespace-name
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:13: error: expected namespace-name before ';' token
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:16: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:19: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:19: error: 'Context' was not declared in this scope
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:19: error: 'context' was not declared in this scope
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:23: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:27: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:31: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:35: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:39: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:48: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:52: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:62: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:68: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:73: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:79: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:87: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:94: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:102: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:109: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:117: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:125: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:134: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:147: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:162: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:171: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:180: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:189: error: expected constructor, destructor, or type conversion before '*' token
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:195: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:208: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:223: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:238: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:262: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:295: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/src/MeldForce.cpp:302: error: invalid use of incomplete type 'class MeldPlugin::MeldForce'
/home-gk/users/nscc1464/wtren/softs/meld-openmm-plugin-master/openmmapi/include/MeldForce.h:21: error: forward declaration of 'class MeldPlugin::MeldForce'
make[2]: *** [CMakeFiles/MeldPlugin.dir/openmmapi/src/MeldForce.cpp.o] Error 1
make[1]: *** [CMakeFiles/MeldPlugin.dir/all] Error 2
make: *** [all] Error 2

It seems that some header files cannot be found. So how can I fix these problems?
PS: I installed openmm7.0 by the pre-compiled binary of OpenMM for Linux

**Comment by jlmaccal** [comment]
@wtren This repository is actually deprecated. The plugin has been rolled into the latest version of MELD at github.com/maccallumlab/meld.

The easiest way to install is to use anaconda:
```
conda create -c omnia -c maccallum_lab -n meld meld-cudaXX
```

Where `XX` is either `75` or `80` for `cuda-7.5` or `cuda-8.0`.

I will mark this repository as deprecated.

**Comment by wtren** [comment]
Hi Justin:

     Thank you for reminding me of that. I have installed latest version
meld on the basis of cuda-6.5

from the source code. Do I need to install higher version of cuda and
rebuilt the meld?


Weitong* Ren, PhD student*
Laboratory of Biophysics
Department of Physics
*Nanjing University*
Nanjing, Jiangsu, PR China
210093
tel : +86 025 8359 7226
*wtren@biophy.nju.edu.cn <wtren@biophy.nju.edu.cn>*
