### ISSUE TITLE
Implementing ambiguous distance restraints using OpenMM

### ISSUE THREAD

**Issue by BIORAK** [maccallumlab/meld-openmm-plugin#4]
I want some thing like the 1/r^6 weighted restraints to restrain atomic distances as used in NMR. But this should be across two different proteins, so it should cause pulling of the proteins. This should be as shown in the paper http://www.tandfonline.com/doi/full/10.1080/00268976.2013.813594 for the case of collective variable (Class IV colvar components: based on multiple pairwise atomic distances, equation 9)

**Comment by jlmaccal** [comment]
Have a look at  [the wiki](https://github.com/maccallumlab/meld-openmm-plugin/wiki). That should give you some idea of what you can do with MELD's forces.

If it is just a single reaction coordinate, it's also possible to do this using a `CustomCompoundBondForce`. However, each force must involve the same number of atoms, so this really only works for defining a single reaction coordinate.

**Comment by BIORAK** [comment]
I am a bit confused with this function r2 = mf.addDistanceRestraint(1, 2, 0, 0.1, 0.1, 999., 1000.0), where do I need to apply the 1/r^6 averaged distances among the atoms of interest in the function. Moreover I want to give an upper bound and lower bound, how do I do it.

**Comment by jlmaccal** [comment]
MELD doesn't allow you to do the r^-6 average, but it allows you to do something similar. The r^-6 restraint is heavily weighted to the shortest distance.

In MELD you can group together multiple restraints and specify that only the lowest energy one at each step is active. This is functionally similar, but not exactly the same as an r^-6 averaged restraint.

For each MELD distance restraint, there are five parameters to specify: r1-r4 and k. If you want a flat-bottom harmonic restraint, set r1=0, r2=lower_bound, r3=upper_bound, and r4=9999. If you want the potentials to be linear beyond certain ranges, set r1 and r4 to those values.

So, to get something similar to an r^-6 restraint, add each distance restraint individually, using the same r1-r4 and k. Then combine them into a group with 1 restraint active.

If you really only want to do r^-6 weighted restraints, then you can do that with a `CustomCompoundBondForce`.

**Comment by BIORAK** [comment]
I am planning to apply the restraints across two different proteins, I saw in your PNAS paper that you get your priors from the AMBER force field so my question is whether this would be applicable when it is applied across two proteins. 

I am not an expert in NMR, so is the upper and lower bound applied after calculating the r^-6 averaged distances among a group of atoms or is it between any two atoms in flat harmonic function. Moreover is the bounds applied same in your package also i.e. among a group or any two atoms. 

I was not able to install your openmm plugin. I am using the anaconda based openmm installation. 

I would also be grateful if you can create an example for r^-6 weighted restraints using CustomCompoundBondForce just like you had it in the adding new forces tutorial. I was unable to figure out how to do it. I am applying it across a group of non bonded atoms in two proteins.

**Comment by jlmaccal** [comment]
> whether this would be applicable when it is applied across two proteins

It's no problem to have the restraints between two proteins.

> Moreover is the bounds applied same in your package also i.e. among a group or any two atoms

Typically in NMR, you would compute the r^-6 averaged distance. This would then have a restraint applied to it. In MELD, each distance has a restraint applied to it, but only the lowest energy (and therefore shortest distance) is active. Functionally, they both achieve the same goal of ensuring that one of the distances is within the specified bounds.

> I was not able to install your openmm plugin. I am using the anaconda based openmm installation.

You will have to give more information if you want help getting it installed. I don't yet have anaconda packages, but it's high on my list of things to do.

> I would also be grateful if you can create an example for r^-6 weighted restraints using CustomCompoundBondForce just like you had it in the adding new forces tutorial.

OK, I'll take a stab at this. No guarantees that it works correctly, but this should get you started. The `Custom*Force` features of OpenMM don't allow for looping. So, you have to write out an expression for the energy explicitly. The code below uses a python function to create the energy expression for you.

```python

from simtk import openmm as omm

# list of atoms in the two groups, indexed starting from zero
# obviously, these need to change for your system
atoms1 = [100, 101]
atoms2 = [200, 242]

energy_function_template = '''
0.5 * k_bond * step(r_eff - r0) * (r_eff - r0)^2;
r_eff = (1.0 / n_pairs * r_sum)^(-1.0 / 6.0);
r_sum = {pair_string};
n_pairs = {n_pairs};
'''

def create_energy_function(atoms1, atoms2):
    n1 = len(atoms1)
    n2 = len(atoms2)
    n_interactions = n1 * n2

    pair_strings = []
    for i in range(n1):
        for j in range(n2):
            pair_strings.append('distance(p{}, p{})^-6'.format(i + 1, n1 + j + 1))
    pair_string = '+'.join(pair_strings)
    return energy_function_template.format(pair_string=pair_string, n_pairs=n_interactions)

energy_function = create_energy_function(atoms1, atoms2)
n_atoms = len(atoms1) + len(atoms2)
force = omm.CustomCompoundBondForce(n_atoms, energy_function)
force.addPerBondParameter('r0')
force.addPerBondParameter('k_bond')

r0 = 0.8  # upper bound in nm
k = 1000  # force constant in kJ / mol / nm^2
force.addBond(atoms1 + atoms2, [r0, k_bond])

system.addForce(force)
```

**Comment by BIORAK** [comment]
Thanks for the CustomForce code. I will try and see if it works.

Ok the problem I get in MELD installation is with respect to the the header files. Anaconda has a separate include directory where it stores the include files of all packages. So even when I export the openmm include path, the header files of openmm are not detected. 

In file included from /home/biorak/Softwares/meld-openmm-plugin/openmmapi/src/MeldForce.cpp:1:0:
/home/biorak/Softwares/meld-openmm-plugin/openmmapi/include/MeldForce.h:4:26: fatal error: openmm/Force.h: No such file or directory
 #include "openmm/Force.h"
