### ISSUE TITLE
Error while installing MELD

### ISSUE THREAD

**Issue by BIORAK** [maccallumlab/meld-openmm-plugin#5]
Hi, I am getting this error when I do PythonInstall

running build
running build_py
running build_ext
building '_meldplugin' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/openmm/include -I/home/biorak/Softwares/meld-openmm-plugin/openmmapi/include -I/home/biorak/Softwares/anaconda/include/python2.7 -c MeldPluginWrapper.cpp -o build/temp.linux-x86_64-2.7/MeldPluginWrapper.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
MeldPluginWrapper.cpp:2884:13: error: ‘ptrdiff_t’ does not name a type
     virtual ptrdiff_t distance(const SwigPyIterator &/*x*/) const
             ^
MeldPluginWrapper.cpp:2921:21: error: expected ‘;’ at end of member declaration
     SwigPyIterator *advance(ptrdiff_t n)
                     ^
MeldPluginWrapper.cpp:2921:39: error: expected ‘)’ before ‘n’
     SwigPyIterator *advance(ptrdiff_t n)
                                       ^
MeldPluginWrapper.cpp:2936:34: error: declaration of ‘operator+=’ as non-function
     SwigPyIterator& operator += (ptrdiff_t n)
                                  ^
MeldPluginWrapper.cpp:2936:30: error: expected ‘;’ at end of member declaration
     SwigPyIterator& operator += (ptrdiff_t n)
                              ^
MeldPluginWrapper.cpp:2936:44: error: expected ‘)’ before ‘n’
     SwigPyIterator& operator += (ptrdiff_t n)
                                            ^
MeldPluginWrapper.cpp:2941:34: error: declaration of ‘operator-=’ as non-function
     SwigPyIterator& operator -= (ptrdiff_t n)
                                  ^
MeldPluginWrapper.cpp:2941:30: error: expected ‘;’ at end of member declaration
     SwigPyIterator& operator -= (ptrdiff_t n)
                              ^
MeldPluginWrapper.cpp:2941:44: error: expected ‘)’ before ‘n’
     SwigPyIterator& operator -= (ptrdiff_t n)
                                            ^
MeldPluginWrapper.cpp:2946:33: error: declaration of ‘operator+’ as non-function
     SwigPyIterator* operator + (ptrdiff_t n) const
                                 ^
MeldPluginWrapper.cpp:2946:30: error: expected ‘;’ at end of member declaration
     SwigPyIterator* operator + (ptrdiff_t n) const
                              ^
MeldPluginWrapper.cpp:2946:43: error: expected ‘)’ before ‘n’
     SwigPyIterator* operator + (ptrdiff_t n) const
                                           ^
MeldPluginWrapper.cpp:2951:33: error: declaration of ‘operator-’ as non-function
     SwigPyIterator* operator - (ptrdiff_t n) const
                                 ^
MeldPluginWrapper.cpp:2951:30: error: expected ‘;’ at end of member declaration
     SwigPyIterator* operator - (ptrdiff_t n) const
                              ^
MeldPluginWrapper.cpp:2951:43: error: expected ‘)’ before ‘n’
     SwigPyIterator* operator - (ptrdiff_t n) const
                                           ^
MeldPluginWrapper.cpp:2956:5: error: ‘ptrdiff_t’ does not name a type
     ptrdiff_t operator - (const SwigPyIterator& x) const
     ^
MeldPluginWrapper.cpp:3112:23: error: ‘SWIG_From_ptrdiff_t’ declared as an ‘inline’ variable
 SWIG_From_ptrdiff_t  (ptrdiff_t value)
                       ^
MeldPluginWrapper.cpp:3112:23: error: ‘ptrdiff_t’ was not declared in this scope
MeldPluginWrapper.cpp:3112:23: note: suggested alternatives:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/exception:37:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/stdexcept:38,
                 from MeldPluginWrapper.cpp:2773:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:1858:28: note:   ‘std::ptrdiff_t’
   typedef __PTRDIFF_TYPE__ ptrdiff_t;
                            ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:1858:28: note:   ‘std::ptrdiff_t’
MeldPluginWrapper.cpp:3113:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {    
 ^
MeldPluginWrapper.cpp:3165:39: error: ‘ptrdiff_t’ has not been declared
 SWIG_AsVal_ptrdiff_t (PyObject * obj, ptrdiff_t *val)
                                       ^
MeldPluginWrapper.cpp: In function ‘int SWIG_AsVal_ptrdiff_t(PyObject*, int*)’:
MeldPluginWrapper.cpp:3169:50: error: expected type-specifier before ‘ptrdiff_t’
   if (SWIG_IsOK(res) && val) *val = static_cast< ptrdiff_t >(v);
                                                  ^
MeldPluginWrapper.cpp:3169:50: error: expected ‘>’ before ‘ptrdiff_t’
MeldPluginWrapper.cpp:3169:50: error: expected ‘(’ before ‘ptrdiff_t’
MeldPluginWrapper.cpp:3169:50: error: ‘ptrdiff_t’ was not declared in this scope
MeldPluginWrapper.cpp:3169:50: note: suggested alternatives:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/exception:37:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/stdexcept:38,
                 from MeldPluginWrapper.cpp:2773:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:1858:28: note:   ‘std::ptrdiff_t’
   typedef __PTRDIFF_TYPE__ ptrdiff_t;
                            ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:1858:28: note:   ‘std::ptrdiff_t’
MeldPluginWrapper.cpp:3169:64: error: expected ‘)’ before ‘;’ token
   if (SWIG_IsOK(res) && val) *val = static_cast< ptrdiff_t >(v);
                                                                ^
MeldPluginWrapper.cpp: At global scope:
MeldPluginWrapper.cpp:3525:15: error: ‘swig::check_index’ declared as an ‘inline’ variable
   check_index(ptrdiff_t i, size_t size, bool insert = false) {
               ^
MeldPluginWrapper.cpp:3525:15: error: ‘ptrdiff_t’ was not declared in this scope
MeldPluginWrapper.cpp:3525:15: note: suggested alternatives:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/exception:37:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/stdexcept:38,
                 from MeldPluginWrapper.cpp:2773:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:1858:28: note:   ‘std::ptrdiff_t’
   typedef __PTRDIFF_TYPE__ ptrdiff_t;
                            ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h:1858:28: note:   ‘std::ptrdiff_t’
MeldPluginWrapper.cpp:3525:35: error: expected primary-expression before ‘size’
   check_index(ptrdiff_t i, size_t size, bool insert = false) {
                                   ^
MeldPluginWrapper.cpp:3525:41: error: expected primary-expression before ‘bool’
   check_index(ptrdiff_t i, size_t size, bool insert = false) {
                                         ^
MeldPluginWrapper.cpp:3525:60: error: expression list treated as compound expression in initializer [-fpermissive]
   check_index(ptrdiff_t i, size_t size, bool insert = false) {
                                                            ^
MeldPluginWrapper.cpp:3525:62: error: expected ‘,’ or ‘;’ before ‘{’ token
   check_index(ptrdiff_t i, size_t size, bool insert = false) {
                                                              ^
In file included from /usr/local/openmm/include/openmm/serialization/SerializationProxy.h:38:0,
                 from /usr/local/openmm/include/openmm/serialization/SerializationNode.h:35,
                 from /usr/local/openmm/include/openmm/serialization/XmlSerializer.h:35,
                 from /usr/local/openmm/include/OpenMM.h:75,
                 from MeldPluginWrapper.cpp:4419:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/typeinfo:39:37: error: expected ‘}’ before end of line
 #pragma GCC visibility push(default)
                                     ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/typeinfo:39:37: error: expected declaration before end of line
error: command 'gcc' failed with exit status 1
make[3]: *** [PythonInstall] Error 1
make[2]: *** [python/CMakeFiles/PythonInstall.dir/all] Error 2
make[1]: *** [python/CMakeFiles/PythonInstall.dir/rule] Error 2
make: *** [PythonInstall] Error 2

**Comment by jlmaccal** [comment]
Can you provide some details about the OS, compiler, version of SWIG, etc?

**Comment by BIORAK** [comment]
CentOS release 6.5
SWIG Version 1.3.40
gcc (GCC) 4.8.2
Python 2.7.10 |Anaconda 2.1.0 (64-bit)
Cuda compilation tools, release 6.5, V6.5.12
